#!/usr/bin/env python3
"""Derive an alpha protection lane without rewriting the historical v1.1 fixture."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
text=(ROOT/'game/tests/cargo_feel_matrix.gd').read_text()
text=text.replace('res://scripts/courier/cargo_observer.gd','res://scripts/courier/alpha_cargo.gd')
text=text.replace('Cargo.new()','new_cargo()')
text=text.replace('for i in 5:', 'for i in 8:')
text=text.replace('event["case"] = row.id', 'event["protection_receipt"] = cargo.loss_receipt.duplicate(true)\n\t\tevent["case"] = row.id')
text+='\nfunc new_cargo() -> RefCounted:\n\tvar observer := Cargo.new()\n\tobserver.protected = "--protected" in OS.get_cmdline_user_args()\n\treturn observer\n'
(ROOT/'game/tests/alpha_cargo_matrix.gd').write_text('# Generated by tools/generate_alpha_cargo_fixture.py; original v1.1 fixture retained.\n'+text)
